apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: loki-experiment
  region: ap-northeast-1
  version: "1.33" # kubernetes のバージョン

addons:
  # PersistentVolumeClaim (PVC) を作成すると自動的に EBS ボリュームが作成されるようになる
  - name: aws-ebs-csi-driver
  # Pod が起動した時に自動的に IAM ロールをアタッチする
  - name: eks-pod-identity-agent

nodeGroups:
  - name: main
    instanceType: "t3.large"
    desiredCapacity: 3
    minSize: 3
    maxSize: 5
    amiFamily: AmazonLinux2023
    iam:
      # EBS CSI Driver が EBS ボリュームを操作するために必要な IAM ポリシーをノードの IAM ロールに自動でアタッチ
      withAddonPolicies:
        ebs: true
    volumeSize: 80 # [GiB]
    volumeType: gp3
    # EC2インスタンス と EBS　ボリューム間のデータ通信専用にネットワーク帯域を確保する
    ebsOptimized: true
